import sqlite3
conn = sqlite3.connect('cars1_db')
c = conn.cursor()
c.execute("DROP TABLE IF EXISTS CAR_TABLE")
c.execute("""CREATE TABLE CAR_TABLE(
        CARNAME CHAR(20) NOT NULL, 
        OWNERNAME CHAR(20) NOT NULL)""")
c.execute("INSERT INTO CAR_TABLE (CARNAME,OWNERNAME) " "VALUES ('SWIFT', 'ANU')")
c.execute("INSERT INTO CAR_TABLE (CARNAME,OWNERNAME) " "VALUES ('ASTER', 'MANU')")
c.execute("INSERT INTO CAR_TABLE (CARNAME,OWNERNAME) " "VALUES ('MARUTHI', ' MEERA')")
c.execute("INSERT INTO CAR_TABLE (CARNAME,OWNERNAME) " "VALUES ('FIGO', 'ARYA')")
c.execute("INSERT INTO CAR_TABLE (CARNAME,OWNERNAME) " "VALUES ('FORTUNER', 'ACHU')")
c.execute("INSERT INTO CAR_TABLE (CARNAME,OWNERNAME) " "VALUES ('POLO', 'AKKU')")
c.execute("INSERT INTO CAR_TABLE (CARNAME,OWNERNAME) " "VALUES ('INNOVA', 'ASA')")
c.execute("INSERT INTO CAR_TABLE (CARNAME,OWNERNAME) " "VALUES ('BELENO', 'IRA')")
c.execute("INSERT INTO CAR_TABLE (CARNAME,OWNERNAME) " "VALUES ('ENTOVOR', 'ISHA')")
c.execute("INSERT INTO CAR_TABLE (CARNAME,OWNERNAME) " "VALUES ('i10', 'IVAN')")
conn.commit()
c = conn.execute("SELECT * from CAR_TABLE")
print(c.fetchall())
conn.close()

